### ISSUE TITLE
Purchasing

### ISSUE THREAD

**Issue by ghost** [hemtjanst/sladdlos#1]
I just read that the bulbs are available for about 35 bucks.

This is super awesome and the mqtt protocol makes this super easy.

I have done a fair bit of orchestration using mqtt and NATS pub sub to allow vents to trigger other events and am grabbing some bulbs to start building code a mobile react native based app.

Can you let me know the current state / roadmap of the project so I can help get aligned to the stuff to do ??

**Comment by bonan** [comment]
In addition to the bulbs, you will need the Trådfri gateway and the Trådfri remote

Right now you need to run [hemtjanst/tradfri-mqtt](https://github.com/hemtjanst/tradfri-mqtt) at the same MQTT broker for this project to be useful - since I have yet to find a golang project that talks CoAP over DTLS. The roadmap includes building direct communications with the Trådfri gateway as soon as I find a CoAP library written in golang that can be used.

You can either use the project as it is, the protocol used over MQTT is documented in the [hemtjanst/hemtjanst](https://github.com/hemtjanst/hemtjanst/blob/master/README.md#specification) project, or you can use it as a library by importing the [tradfri](https://github.com/hemtjanst/sladdlos/tree/master/tradfri) and [transport](https://github.com/hemtjanst/sladdlos/tree/master/transport) packages

**Comment by ghost** [comment]
thanks @bonan 

that helps allot. I will dig in.

I saw a few COAP libs around but never looked for DTLS.. Sure we can rope something together.
